framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:    # Cette option définit la locale de secours à utiliser quand une traduction n'existe pas dans le local de l'utilisateur.
            - '%locale%'
