framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:    # Cette option définit le locale de secours à utiliser quand une traduction n'existe pas dans le local de l'utilisateur.
            - en
