vich_uploader:
    db_driver: orm
    mappings:
        lesson_images:   # Le nom du chemin qui contient la configuration d'un mappage spécifique. Elles sont stockées les images téléchargées.
            uri_prefix: '%app.path.lesson_images%'  # /uploads/lesson_pictures Le chemin vers lequel le fichier doit aller
            namer: Vich\UploaderBundle\Naming\UniqidNamer    # est un outil intégré à vich uploader qui permet de renommer les fichiers de façon unique c'est à dire que deux fichiers n'auront pas le même nom
            upload_destination: '%kernel.project_dir%/public/%app.path.lesson_images%'  # uploads/lesson_pictures'  L'endroit ou stocker les images
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
